name: Test

on:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - '.github/workflows/test.yml'

jobs:
  parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm test
